/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.DriverManager;
import javax.swing.table.TableModel;

 
/**
 *
 * @author admin
 */
public class Entereprise extends javax.swing.JFrame {
     
    
    Connection con =null ;
    Statement  stt=null;
    PreparedStatement add =null , st=null;
     ResultSet res=null;
     
    /**
     * Creates new form Agents
     */
    public Entereprise() {
        initComponents();
        SelectedMed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextIDEnt = new javax.swing.JTextField();
        jTextNomEnt = new javax.swing.JTextField();
        jBtnModifierEnt = new javax.swing.JButton();
        jBTNAjouterEnt = new javax.swing.JButton();
        jBtnSupprimerEnt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntrprise = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jBtnAnnulerEnt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextAdrsEnt = new javax.swing.JTextField();
        jTextTelEnt = new javax.swing.JTextField();
        jTextExpEnt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/k.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(55, 169, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 169, 53));
        jLabel5.setText("ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 72, 29));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 169, 53));
        jLabel7.setText("Nom");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 115, 29));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 169, 53));
        jLabel8.setText("Addresse");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 104, 29));

        jTextIDEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextIDEnt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jTextIDEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDEntActionPerformed(evt);
            }
        });
        jPanel2.add(jTextIDEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 90, 290, 29));

        jTextNomEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextNomEnt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jPanel2.add(jTextNomEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 130, 290, 29));

        jBtnModifierEnt.setBackground(new java.awt.Color(55, 169, 53));
        jBtnModifierEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnModifierEnt.setForeground(new java.awt.Color(255, 255, 255));
        jBtnModifierEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ModiferEntreprise.png"))); // NOI18N
        jBtnModifierEnt.setText("Modifier");
        jBtnModifierEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnModifierEntMouseClicked(evt);
            }
        });
        jBtnModifierEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModifierEntActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnModifierEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, 50));

        jBTNAjouterEnt.setBackground(new java.awt.Color(55, 169, 53));
        jBTNAjouterEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBTNAjouterEnt.setForeground(new java.awt.Color(255, 255, 255));
        jBTNAjouterEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/AjouterEntreprise.png"))); // NOI18N
        jBTNAjouterEnt.setText("Ajouter");
        jBTNAjouterEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNAjouterEntMouseClicked(evt);
            }
        });
        jBTNAjouterEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNAjouterEntActionPerformed(evt);
            }
        });
        jPanel2.add(jBTNAjouterEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 144, 50));

        jBtnSupprimerEnt.setBackground(new java.awt.Color(55, 169, 53));
        jBtnSupprimerEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnSupprimerEnt.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSupprimerEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/supprimer.png"))); // NOI18N
        jBtnSupprimerEnt.setText("Supprimer");
        jBtnSupprimerEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSupprimerEntMouseClicked(evt);
            }
        });
        jBtnSupprimerEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprimerEntActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnSupprimerEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, 50));

        jTableEntrprise.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 0), null));
        jTableEntrprise.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTableEntrprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Experiance", "Tel", "Adresse"
            }
        ));
        jTableEntrprise.setSelectionBackground(new java.awt.Color(51, 255, 0));
        jTableEntrprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEntrpriseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEntrprise);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 766, 146));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 169, 53));
        jLabel10.setText("LISTE D'ENTREPRISE");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, 35));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 169, 53));
        jLabel11.setText("Exeperiance");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 115, 29));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(55, 169, 53));
        jLabel14.setText("Tel");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 115, 29));

        jBtnAnnulerEnt.setBackground(new java.awt.Color(55, 169, 53));
        jBtnAnnulerEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnAnnulerEnt.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAnnulerEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/vider.png"))); // NOI18N
        jBtnAnnulerEnt.setText("Vider");
        jBtnAnnulerEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnnulerEntMouseClicked(evt);
            }
        });
        jBtnAnnulerEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerEntActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAnnulerEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 130, 50));

        jPanel3.setBackground(new java.awt.Color(55, 169, 53));

        jLabel4.setBackground(new java.awt.Color(55, 169, 53));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/EntrepriseLogo.png"))); // NOI18N
        jLabel4.setText("GESTION D'ENTREPRISE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 380, 70));

        jPanel4.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, 10));

        jPanel5.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jPanel6.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jPanel9.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 220, -1));

        jPanel7.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 260, 10));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 169, 53)));

        jTextAdrsEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextAdrsEnt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jTextAdrsEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAdrsEntActionPerformed(evt);
            }
        });

        jTextTelEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextTelEnt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));

        jTextExpEnt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextExpEnt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jTextExpEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExpEntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextExpEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTelEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAdrsEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jTextExpEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextTelEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextAdrsEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 510, 250));

        jPanel10.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, 880, 630));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/AgentLogo.png"))); // NOI18N
        jLabel1.setText("Agents");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 168, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/MedicamentLogo.png"))); // NOI18N
        jLabel2.setText("Medicament");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/VenteLogo.png"))); // NOI18N
        jLabel3.setText("Vente");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 168, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/k.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -140, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/k.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     public void SelectedMed(){
          try{
              con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
              stt =con.createStatement();
              res = stt.executeQuery("Select * from entreprise");
              jTableEntrprise.setModel(DbUtils.resultSetToTableModel(res));
          
          }catch(SQLException e){
              e.printStackTrace();
          
          }
    }
    private void jTextIDEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDEntActionPerformed

    private void jBtnModifierEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifierEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnModifierEntActionPerformed

    private void jBTNAjouterEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNAjouterEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTNAjouterEntActionPerformed

    private void jBtnSupprimerEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprimerEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSupprimerEntActionPerformed

    private void jBTNAjouterEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNAjouterEntMouseClicked
            try{
            
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
           add = con.prepareStatement("INSERT INTO entreprise(IdEntr, NomEnt, ExpEnt, TelEnt, AdrsEnt)  VALUES(?,?,?,?,?)");

            add.setInt(1, Integer.parseInt(jTextIDEnt.getText()));
            add.setString(2,jTextNomEnt.getText());
            add.setString(3,jTextExpEnt.getText());
            add.setInt(4, Integer.parseInt(jTextTelEnt.getText()));
            add.setString(5,jTextAdrsEnt.getText());
            
         int rowsAffected = add.executeUpdate();
             if (rowsAffected > 0) {
                 JOptionPane.showMessageDialog(this, "Entreprise ajouté avec succès");
              } else {
                  JOptionPane.showMessageDialog(this, "Échec de l'ajout d'entreprise");
               }
             
             con.close();
             SelectedMed();
            
            
        //JOptionPane.showMessageDialog(this, "Médicament ajouté avec succès");
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout d'entreprise : " + e.getMessage());

    }
    
    }//GEN-LAST:event_jBTNAjouterEntMouseClicked

    private void jTextAdrsEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAdrsEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAdrsEntActionPerformed

    private void jBtnSupprimerEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSupprimerEntMouseClicked
        if(jTextIDEnt.getText().isEmpty()){
                 JOptionPane.showMessageDialog(this, " Entrer (ID) d'entreprise supprimer");
          }else{
          
          try{
              
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
              String id = jTextIDEnt.getText();
              String sql = "DELETE FROM  entreprise WHERE IdEntr="+id;
              Statement add = con.createStatement();
              add.executeUpdate(sql);
              JOptionPane.showMessageDialog(this, "Entreprise Supprimer avec succès");
              SelectedMed();
              con.close();
              
          }catch(SQLException e){
                 e.printStackTrace();
          }
          
        }
    }//GEN-LAST:event_jBtnSupprimerEntMouseClicked

    private void jBtnModifierEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModifierEntMouseClicked
       if(jTextNomEnt.getText().isEmpty() || jTextExpEnt.getText().isEmpty() || jTextTelEnt.getText().isEmpty() || jTextAdrsEnt.getText().isEmpty() || jTextIDEnt.getText().isEmpty()){
            
            
            JOptionPane.showMessageDialog(this, "Demblir les champs ");
        
        }else{
            try {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "");

    String sql =  "UPDATE entreprise SET NomEnt=?, ExpEnt=?, TelEnt=?, AdrsEnt=? WHERE IdEntr = ?";

    st = con.prepareStatement(sql);
    st.setString(1, jTextNomEnt.getText());
    st.setString(2, jTextExpEnt.getText());
    st.setInt(3, Integer.parseInt(jTextTelEnt.getText()));
    st.setString(4, jTextAdrsEnt.getText());
    st.setInt(5, Integer.parseInt(jTextIDEnt.getText()));

    int rowsUpdated = st.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(this, " Entreprise mis à jour avec succès");
    } else {
        JOptionPane.showMessageDialog(this, "Impossible de mettre à jour l'entreprise");
    }
    con.close();
     
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour du entreprise");
}
        SelectedMed();
        }                                           
 
    }//GEN-LAST:event_jBtnModifierEntMouseClicked

    private void jTableEntrpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEntrpriseMouseClicked
       TableModel model = jTableEntrprise.getModel();
    int i = jTableEntrprise.getSelectedRow();  // Utiliser getSelectedRow() pour obtenir la ligne sélectionnée

    if (i != -1) {  // Vérifier si une ligne est sélectionnée
        jTextIDEnt.setText(model.getValueAt(i, 0).toString());
        jTextNomEnt.setText(model.getValueAt(i, 1).toString());
        jTextExpEnt.setText(model.getValueAt(i, 2).toString());
        jTextTelEnt.setText(model.getValueAt(i, 3).toString());
        jTextAdrsEnt.setText(model.getValueAt(i, 4).toString());
    }
    }//GEN-LAST:event_jTableEntrpriseMouseClicked

    private void jBtnAnnulerEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnulerEntMouseClicked
        jTextIDEnt.setText("");
        jTextNomEnt.setText("");
        jTextTelEnt.setText("");
        jTextAdrsEnt.setText("");
        jTextExpEnt.setText("");
        

    }//GEN-LAST:event_jBtnAnnulerEntMouseClicked

    private void jBtnAnnulerEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAnnulerEntActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new Midcine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Agent().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         new Vente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTextExpEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExpEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExpEntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entereprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entereprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entereprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entereprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entereprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNAjouterEnt;
    private javax.swing.JButton jBtnAnnulerEnt;
    private javax.swing.JButton jBtnModifierEnt;
    private javax.swing.JButton jBtnSupprimerEnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEntrprise;
    private javax.swing.JTextField jTextAdrsEnt;
    private javax.swing.JTextField jTextExpEnt;
    private javax.swing.JTextField jTextIDEnt;
    private javax.swing.JTextField jTextNomEnt;
    private javax.swing.JTextField jTextTelEnt;
    // End of variables declaration//GEN-END:variables
}
