
package pharmacy;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.util.Date;

public final class Midcine extends javax.swing.JFrame {
   
    
    Connection con =null ;
    Statement  stt=null;
    PreparedStatement add =null , st=null;
     ResultSet res=null;       
    /**
     * Creates new form Midcine
     */
    public Midcine() {
        initComponents();
        SelectedMed();
        GetEntreprise();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextQte = new javax.swing.JTextField();
        jTextIdMed = new javax.swing.JTextField();
        jTexPrix = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCombEntreprise = new javax.swing.JComboBox<>();
        jTextMedicament = new javax.swing.JTextField();
        jDateEXP = new com.toedter.calendar.JDateChooser();
        jDateFAB = new com.toedter.calendar.JDateChooser();
        jButtonModifier = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMed = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jBtnAnnulerAg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 169, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 169, 53));
        jLabel5.setText("ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 93, 72, 29));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(55, 169, 53));
        jLabel6.setText("Entreprise");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 115, 29));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 169, 53));
        jLabel7.setText("Medicament");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 132, 115, 29));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 169, 53));
        jLabel8.setText("Prix");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 180, 115, 29));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(55, 169, 53));
        jLabel9.setText("Quntite");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 228, 115, 29));

        jTextQte.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextQte.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jPanel2.add(jTextQte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 216, 29));

        jTextIdMed.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextIdMed.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jTextIdMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdMedActionPerformed(evt);
            }
        });
        jPanel2.add(jTextIdMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 216, 29));

        jTexPrix.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTexPrix.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jPanel2.add(jTexPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 216, 29));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 169, 53));
        jLabel11.setText("FABDate");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 115, 29));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(55, 169, 53));
        jLabel12.setText("EXPDate");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 115, 29));

        jCombEntreprise.setBackground(new java.awt.Color(55, 169, 53));
        jCombEntreprise.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jCombEntreprise.setForeground(new java.awt.Color(255, 255, 255));
        jCombEntreprise.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jPanel2.add(jCombEntreprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 230, 30));

        jTextMedicament.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextMedicament.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jPanel2.add(jTextMedicament, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 216, 29));

        jDateEXP.setBackground(new java.awt.Color(55, 169, 53));
        jDateEXP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jDateEXP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(jDateEXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 153, 230, 30));

        jDateFAB.setBackground(new java.awt.Color(55, 169, 53));
        jDateFAB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(55, 169, 53), null));
        jDateFAB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(jDateFAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 228, 29));

        jButtonModifier.setBackground(new java.awt.Color(55, 169, 53));
        jButtonModifier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonModifier.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ModifierMedicament.png"))); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModifierMouseClicked(evt);
            }
        });
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 281, 158, 50));

        jButtonAjouter.setBackground(new java.awt.Color(55, 169, 53));
        jButtonAjouter.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonAjouter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/AjouterMedecament.png"))); // NOI18N
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAjouterMouseClicked(evt);
            }
        });
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 281, 150, 50));

        jButtonSupprimer.setBackground(new java.awt.Color(55, 169, 53));
        jButtonSupprimer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/supprimer.png"))); // NOI18N
        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSupprimerMouseClicked(evt);
            }
        });
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 281, -1, 50));

        jTableMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        jTableMed.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTableMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Medicament", "Prix", "Qantite", "DateFAB", "QateEXP", "Entreprise"
            }
        ));
        jTableMed.setGridColor(new java.awt.Color(242, 242, 242));
        jTableMed.setSelectionBackground(new java.awt.Color(51, 255, 0));
        jTableMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMed);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 426, 860, 158));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 169, 53));
        jLabel10.setText("LISTE DE MEDICAMENT");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 373, -1, 35));

        jBtnAnnulerAg.setBackground(new java.awt.Color(55, 169, 53));
        jBtnAnnulerAg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnAnnulerAg.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAnnulerAg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/vider.png"))); // NOI18N
        jBtnAnnulerAg.setText("Vider");
        jBtnAnnulerAg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnnulerAgMouseClicked(evt);
            }
        });
        jBtnAnnulerAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerAgActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAnnulerAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 281, 120, 50));

        jPanel3.setBackground(new java.awt.Color(55, 169, 53));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-medicine-64.png"))); // NOI18N
        jLabel4.setText("GESTION DE MEDICAMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel5.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 210, -1));

        jPanel6.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 850, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 890, 650));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/AgentLogo.png"))); // NOI18N
        jLabel1.setText("Agents");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 168, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/enterepriseLogo.png"))); // NOI18N
        jLabel2.setText("Entreprise");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/VenteLogo.png"))); // NOI18N
        jLabel3.setText("Vente");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 168, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("X");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 6, 26, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/k.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -130, -1, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SelectedMed(){
          try{
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
              stt =con.createStatement();
              res = stt.executeQuery("Select * from medcine");
              jTableMed.setModel(DbUtils.resultSetToTableModel(res));
          
          }catch(SQLException e){
              e.printStackTrace();
          
          }
    }
    
    public void GetEntreprise(){
    try{
      
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
        stt =con.createStatement();
        res = stt.executeQuery("Select * from entreprise");
        int a=0 ;
            if(a==0){
                jCombEntreprise.addItem("");
                a++;
            }
        while(res.next()){
            
                String name = res.getString("NomEnt");
                jCombEntreprise.addItem(name);
        }
    }catch(SQLException e){
              e.printStackTrace();
          
          }
    }
    private void jTextIdMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdMedActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        
             
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAjouterMouseClicked
        try{
            
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
           add = con.prepareStatement("INSERT INTO medcine(IdMed, MedicamemtMed, PrixMed, QteMed, FabDateMed, ExpDateMed, EntrepriseMed)  VALUES(?,?,?,?,?,?,?)");

            add.setInt(1, Integer.parseInt(jTextIdMed.getText()));
            add.setString(2,jTextMedicament.getText());
            add.setString(3,jTexPrix.getText());
            add.setString(4,jTextQte.getText());
            
            if (jDateFAB.getDate() != null && jDateEXP.getDate() != null) {
                 add.setDate(5, new java.sql.Date(jDateFAB.getDate().getTime()));
                 add.setDate(6, new java.sql.Date(jDateEXP.getDate().getTime()));
            } else {
                JOptionPane.showMessageDialog(this, "la date est vide");
    // Gérer le cas où les dates sont nulles
                  }
           
            add.setString(7,jCombEntreprise.getSelectedItem().toString());
            
            
         int rowsAffected = add.executeUpdate();
             if (rowsAffected > 0) {
                 JOptionPane.showMessageDialog(this, "Médicament ajouté avec succès");
              } else {
                  JOptionPane.showMessageDialog(this, "Échec de l'ajout du médicament");
               }
             
             con.close();
             SelectedMed();
            
            
        //JOptionPane.showMessageDialog(this, "Médicament ajouté avec succès");
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout du médicament : " + e.getMessage());

    }
    
    }//GEN-LAST:event_jButtonAjouterMouseClicked

    private void jButtonSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSupprimerMouseClicked
          if(jTextIdMed.getText().isEmpty()){
                 JOptionPane.showMessageDialog(this, " Entrer (ID) de médicament supprimer");
          }else{
          
          try{
              
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
              String id = jTextIdMed.getText();
              String sql = "DELETE FROM medcine WHERE IdMed="+id;
              Statement add = con.createStatement();
              add.executeUpdate(sql);
              JOptionPane.showMessageDialog(this, "Médicament Supprimer avec succès");
              
              con.close();
              SelectedMed();
              
          }catch(SQLException e){
                 e.printStackTrace();
          }
          
        }
    }//GEN-LAST:event_jButtonSupprimerMouseClicked

    private void jButtonModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModifierMouseClicked
       if (jTextIdMed.getText().isEmpty() || 
        jDateFAB.getDate() == null || 
        jDateEXP.getDate() == null || 
        jTextMedicament.getText().isEmpty() || 
        jTexPrix.getText().isEmpty() || 
        jTextQte.getText().isEmpty() ||
        jCombEntreprise.getSelectedItem().toString().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.");
        }else{
            try {
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "");

    String sql = "UPDATE medcine SET "
            + "MedicamemtMed=?, "
            + "PrixMed=?, "
            + "QteMed=?, "
            + "FabDateMed=?, "
            + "ExpDateMed=?, "
            + "EntrepriseMed=? "
            + "WHERE IdMed=?";

    st = con.prepareStatement(sql);
    st.setString(1, jTextMedicament.getText());
    st.setString(2, jTexPrix.getText());
    st.setString(3, jTextQte.getText());
    st.setDate(4, new java.sql.Date(jDateFAB.getDate().getTime()));
    st.setDate(5, new java.sql.Date(jDateEXP.getDate().getTime()));
    st.setString(6, jCombEntreprise.getSelectedItem().toString());
    st.setInt(7, Integer.parseInt(jTextIdMed.getText()));

    int rowsUpdated = st.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(this, "Médicament mis à jour avec succès");
    } else {
        JOptionPane.showMessageDialog(this, "Impossible de mettre à jour le médicament");
    }
    con.close();
     
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour du médicament");
}
        SelectedMed();
        }
        
        
    }//GEN-LAST:event_jButtonModifierMouseClicked

    private void jTableMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedMouseClicked
        TableModel model = jTableMed.getModel();
        int i = jTableMed.getSelectedRow();  
        if (i != -1) {
        jTextIdMed.setText(model.getValueAt(i, 0).toString()); 
        jTextMedicament.setText(model.getValueAt(i, 1).toString()); 
        jTexPrix.setText(model.getValueAt(i, 2).toString()); 
        jTextQte.setText(model.getValueAt(i, 3).toString()); 
        jDateFAB.setDate((Date) model.getValueAt(i, 4)); 
        jDateEXP.setDate((Date) model.getValueAt(i, 5)); 
        jCombEntreprise.setSelectedItem(model.getValueAt(i, 6)); 
    }
    }//GEN-LAST:event_jTableMedMouseClicked

    private void jBtnAnnulerAgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnulerAgMouseClicked
        jTextMedicament.setText("");
        jTextQte.setText("");
        jTextIdMed.setText("");
        jTexPrix.setText("");
        jDateFAB.setDate(null);
        jDateEXP.setDate(null);
        jCombEntreprise.setSelectedItem("");
    }//GEN-LAST:event_jBtnAnnulerAgMouseClicked

    private void jBtnAnnulerAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAnnulerAgActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Vente v =new Vente();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       new Entereprise().setVisible(true);
       this.dispose();
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Agent().setVisible(true);
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Midcine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Midcine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Midcine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Midcine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Midcine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnnulerAg;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox<String> jCombEntreprise;
    private com.toedter.calendar.JDateChooser jDateEXP;
    private com.toedter.calendar.JDateChooser jDateFAB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMed;
    private javax.swing.JTextField jTexPrix;
    private javax.swing.JTextField jTextIdMed;
    private javax.swing.JTextField jTextMedicament;
    private javax.swing.JTextField jTextQte;
    // End of variables declaration//GEN-END:variables
  
}
