/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.TableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Vente extends javax.swing.JFrame {
     private String formattedDate;
    /**
     * Creates new form inde
     */
    public Vente() {
        initComponents();
        SelectedMed();
        DateAfficher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextMedicament = new javax.swing.JTextField();
        jTextIdMed = new javax.swing.JTextField();
        jBtnImprimer = new javax.swing.JButton();
        jBtnAjtFacture = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMed = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jBtnAnnulerAg = new javax.swing.JButton();
        jTextQte1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFacture = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jDate = new javax.swing.JLabel();
        jDate1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1081, 650));

        jPanel1.setBackground(new java.awt.Color(55, 169, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(878, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 169, 53));
        jLabel5.setText("ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 72, 29));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(55, 169, 53));
        jLabel9.setText("Medicament");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 115, 29));

        jTextMedicament.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextMedicament.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 0), null));
        jPanel2.add(jTextMedicament, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 161, 29));

        jTextIdMed.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextIdMed.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 0), null));
        jTextIdMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdMedActionPerformed(evt);
            }
        });
        jPanel2.add(jTextIdMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 163, 29));

        jBtnImprimer.setBackground(new java.awt.Color(55, 169, 53));
        jBtnImprimer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnImprimer.setForeground(new java.awt.Color(255, 255, 255));
        jBtnImprimer.setText("Imprimer");
        jBtnImprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnImprimerMouseClicked(evt);
            }
        });
        jBtnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImprimerActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnImprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 140, 38));

        jBtnAjtFacture.setBackground(new java.awt.Color(55, 169, 53));
        jBtnAjtFacture.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnAjtFacture.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAjtFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/AjouterFacture.png"))); // NOI18N
        jBtnAjtFacture.setText("Ajouter a la facture");
        jBtnAjtFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAjtFactureMouseClicked(evt);
            }
        });
        jBtnAjtFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjtFactureActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAjtFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 250, 50));

        jTableMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        jTableMed.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTableMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Medicament", "Prix", "Qantite", "DateFAB", "QateEXP", "Entreprise"
            }
        ));
        jTableMed.setGridColor(new java.awt.Color(242, 242, 242));
        jTableMed.setSelectionBackground(new java.awt.Color(51, 255, 0));
        jTableMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMed);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 480, 120));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(55, 169, 53));
        jLabel10.setText("LISTE DE MEDICAMENT");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, 35));

        jBtnAnnulerAg.setBackground(new java.awt.Color(55, 169, 53));
        jBtnAnnulerAg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtnAnnulerAg.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAnnulerAg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/supprimer.png"))); // NOI18N
        jBtnAnnulerAg.setText("Vider");
        jBtnAnnulerAg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAnnulerAgMouseClicked(evt);
            }
        });
        jBtnAnnulerAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerAgActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAnnulerAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 110, 40));

        jTextQte1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextQte1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 0), null));
        jPanel2.add(jTextQte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 161, 29));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 169, 53));
        jLabel11.setText("Quntite");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 115, 29));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(55, 169, 53));
        jLabel12.setText("La Facture :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, 35));

        jTextAreaFacture.setColumns(20);
        jTextAreaFacture.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextAreaFacture.setRows(5);
        jTextAreaFacture.setText("                       *****************************Pharmacie*****************************");
        jTextAreaFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaFactureMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaFacture);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 691, 200));

        jPanel3.setBackground(new java.awt.Color(55, 169, 53));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VENTE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, 40));

        jPanel4.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 10));

        jPanel5.setBackground(new java.awt.Color(55, 169, 53));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 550, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 850, 150));

        jDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDate.setForeground(new java.awt.Color(0, 153, 0));
        jDate.setText("Date");
        jPanel2.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        jDate1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDate1.setForeground(new java.awt.Color(0, 153, 0));
        jDate1.setText("Date");
        jPanel2.add(jDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 0, 950, 688));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/AgentLogo.png"))); // NOI18N
        jLabel1.setText("Agent");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/enterepriseLogo.png"))); // NOI18N
        jLabel2.setText("Entreprise");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 70));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/MedicamentLogo.png"))); // NOI18N
        jLabel7.setText("Medicament");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/k.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con =null ;
    Statement  stt=null;
    PreparedStatement add =null , st=null;
     ResultSet res=null;  
     
     public void DateAfficher(){
          
         Date d = new Date();
         SimpleDateFormat sD = new SimpleDateFormat("dd-MM-yyyy");
         formattedDate = sD.format(d);
         jDate1.setText(formattedDate);
     }
     
     public void SelectedMed(){
          try{
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","");
              stt =con.createStatement();
              res = stt.executeQuery("Select * from medcine");
              jTableMed.setModel(DbUtils.resultSetToTableModel(res));
          
          }catch(SQLException e){
              e.printStackTrace();
          
          }
    }
    private void jBtnImprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnImprimerMouseClicked
      try{
        jTextAreaFacture.print();
      } catch (PrinterException ex) {
            Logger.getLogger(Vente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnImprimerMouseClicked

    private void jBtnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnImprimerActionPerformed
     int a = 0;
     float Prix;
    private void jBtnAjtFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAjtFactureMouseClicked
         if(jTextMedicament.getText().isEmpty() || jTextIdMed.getText().isEmpty() || jTextQte1.getText().isEmpty() ){
              JOptionPane.showMessageDialog(this, "Demblir les champs ");
         }else{
        a++;
         if(a==1){
        jTextAreaFacture.setText("         ---"+formattedDate+"---*****************************Pharmacie*****************************\n\n \tID           Medicament           Quntite           Prix           Total\n\t"+a+"              "+jTextMedicament.getText()+"               "+jTextQte1.getText()+"               "+Prix+"         "+ Prix*(Integer.parseInt(jTextQte1.getText()))+"\n");
        }else{
        jTextAreaFacture.setText(jTextAreaFacture.getText()+"\t"+a+"\t"+jTextMedicament.getText()+"            "+jTextQte1.getText()+"          "+Prix+"        "+ Prix * Integer.parseInt(jTextQte1.getText())+"\n");
        }
         }
    }//GEN-LAST:event_jBtnAjtFactureMouseClicked

    private void jBtnAjtFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjtFactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAjtFactureActionPerformed

    private void jTableMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedMouseClicked
        TableModel model = jTableMed.getModel();
        int i = jTableMed.getSelectedRow();
        if(i != -1){
        jTextIdMed.setText(model.getValueAt(i, 0).toString());
        jTextMedicament.setText(model.getValueAt(i,1).toString());
        Prix = ((float) model.getValueAt(i,2));
        jTextQte1.setText(model.getValueAt(i,3).toString());
        
        }

    }//GEN-LAST:event_jTableMedMouseClicked

    private void jBtnAnnulerAgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnulerAgMouseClicked
        jTextMedicament.setText("");
        jTextIdMed.setText("");
        jTextQte1.setText("");
    }//GEN-LAST:event_jBtnAnnulerAgMouseClicked

    private void jBtnAnnulerAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAnnulerAgActionPerformed

    private void jTextIdMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdMedActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Midcine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         new Entereprise().setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Agent().setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextAreaFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaFactureMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextAreaFactureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Vente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAjtFacture;
    private javax.swing.JButton jBtnAnnulerAg;
    private javax.swing.JButton jBtnImprimer;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMed;
    private javax.swing.JTextArea jTextAreaFacture;
    private javax.swing.JTextField jTextIdMed;
    private javax.swing.JTextField jTextMedicament;
    private javax.swing.JTextField jTextQte1;
    // End of variables declaration//GEN-END:variables
}
